/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R404RouteImport } from './routes/404'
import { Route as BulkUploadRouteImport } from './routes/bulk-upload'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MapRouteImport } from './routes/map'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SmartDriveRouteImport } from './routes/smart-drive'
import { Route as UploadHubRouteImport } from './routes/upload-hub'
import { Route as VolunteerDashboardRouteImport } from './routes/volunteer-dashboard'
import { Route as NeedsIndexRouteImport } from './routes/needs/index'
import { Route as NeedsIdRouteImport } from './routes/needs/$id'
import { Route as NeedsNewRouteImport } from './routes/needs/new'
import { Route as SurveysIndexRouteImport } from './routes/surveys/index'
import { Route as SurveysIdRouteImport } from './routes/surveys/$id'
import { Route as SurveysNewRouteImport } from './routes/surveys/new'
import { Route as VolunteersIndexRouteImport } from './routes/volunteers/index'
import { Route as VolunteersIdRouteImport } from './routes/volunteers/$id'
import { Route as VolunteersNewRouteImport } from './routes/volunteers/new'
import { Route as FormsIdViewRouteImport } from './routes/forms/$id/view'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const BulkUploadRoute = BulkUploadRouteImport.update({
  id: '/bulk-upload',
  path: '/bulk-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartDriveRoute = SmartDriveRouteImport.update({
  id: '/smart-drive',
  path: '/smart-drive',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadHubRoute = UploadHubRouteImport.update({
  id: '/upload-hub',
  path: '/upload-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerDashboardRoute = VolunteerDashboardRouteImport.update({
  id: '/volunteer-dashboard',
  path: '/volunteer-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const NeedsIndexRoute = NeedsIndexRouteImport.update({
  id: '/needs/',
  path: '/needs/',
  getParentRoute: () => rootRouteImport,
} as any)
const NeedsIdRoute = NeedsIdRouteImport.update({
  id: '/needs/$id',
  path: '/needs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const NeedsNewRoute = NeedsNewRouteImport.update({
  id: '/needs/new',
  path: '/needs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveysIndexRoute = SurveysIndexRouteImport.update({
  id: '/surveys/',
  path: '/surveys/',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveysIdRoute = SurveysIdRouteImport.update({
  id: '/surveys/$id',
  path: '/surveys/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveysNewRoute = SurveysNewRouteImport.update({
  id: '/surveys/new',
  path: '/surveys/new',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteersIndexRoute = VolunteersIndexRouteImport.update({
  id: '/volunteers/',
  path: '/volunteers/',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteersIdRoute = VolunteersIdRouteImport.update({
  id: '/volunteers/$id',
  path: '/volunteers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteersNewRoute = VolunteersNewRouteImport.update({
  id: '/volunteers/new',
  path: '/volunteers/new',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsIdViewRoute = FormsIdViewRouteImport.update({
  id: '/forms/$id/view',
  path: '/forms/$id/view',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/bulk-upload': typeof BulkUploadRoute
  '/change-password': typeof ChangePasswordRoute
  '/chat': typeof ChatRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/settings': typeof SettingsRoute
  '/smart-drive': typeof SmartDriveRoute
  '/upload-hub': typeof UploadHubRoute
  '/volunteer-dashboard': typeof VolunteerDashboardRoute
  '/needs/$id': typeof NeedsIdRoute
  '/needs/new': typeof NeedsNewRoute
  '/surveys/$id': typeof SurveysIdRoute
  '/surveys/new': typeof SurveysNewRoute
  '/volunteers/$id': typeof VolunteersIdRoute
  '/volunteers/new': typeof VolunteersNewRoute
  '/needs/': typeof NeedsIndexRoute
  '/surveys/': typeof SurveysIndexRoute
  '/volunteers/': typeof VolunteersIndexRoute
  '/forms/$id/view': typeof FormsIdViewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/bulk-upload': typeof BulkUploadRoute
  '/change-password': typeof ChangePasswordRoute
  '/chat': typeof ChatRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/settings': typeof SettingsRoute
  '/smart-drive': typeof SmartDriveRoute
  '/upload-hub': typeof UploadHubRoute
  '/volunteer-dashboard': typeof VolunteerDashboardRoute
  '/needs/$id': typeof NeedsIdRoute
  '/needs/new': typeof NeedsNewRoute
  '/surveys/$id': typeof SurveysIdRoute
  '/surveys/new': typeof SurveysNewRoute
  '/volunteers/$id': typeof VolunteersIdRoute
  '/volunteers/new': typeof VolunteersNewRoute
  '/needs': typeof NeedsIndexRoute
  '/surveys': typeof SurveysIndexRoute
  '/volunteers': typeof VolunteersIndexRoute
  '/forms/$id/view': typeof FormsIdViewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/bulk-upload': typeof BulkUploadRoute
  '/change-password': typeof ChangePasswordRoute
  '/chat': typeof ChatRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/settings': typeof SettingsRoute
  '/smart-drive': typeof SmartDriveRoute
  '/upload-hub': typeof UploadHubRoute
  '/volunteer-dashboard': typeof VolunteerDashboardRoute
  '/needs/$id': typeof NeedsIdRoute
  '/needs/new': typeof NeedsNewRoute
  '/surveys/$id': typeof SurveysIdRoute
  '/surveys/new': typeof SurveysNewRoute
  '/volunteers/$id': typeof VolunteersIdRoute
  '/volunteers/new': typeof VolunteersNewRoute
  '/needs/': typeof NeedsIndexRoute
  '/surveys/': typeof SurveysIndexRoute
  '/volunteers/': typeof VolunteersIndexRoute
  '/forms/$id/view': typeof FormsIdViewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/bulk-upload'
    | '/change-password'
    | '/chat'
    | '/login'
    | '/map'
    | '/settings'
    | '/smart-drive'
    | '/upload-hub'
    | '/volunteer-dashboard'
    | '/needs/$id'
    | '/needs/new'
    | '/surveys/$id'
    | '/surveys/new'
    | '/volunteers/$id'
    | '/volunteers/new'
    | '/needs/'
    | '/surveys/'
    | '/volunteers/'
    | '/forms/$id/view'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/bulk-upload'
    | '/change-password'
    | '/chat'
    | '/login'
    | '/map'
    | '/settings'
    | '/smart-drive'
    | '/upload-hub'
    | '/volunteer-dashboard'
    | '/needs/$id'
    | '/needs/new'
    | '/surveys/$id'
    | '/surveys/new'
    | '/volunteers/$id'
    | '/volunteers/new'
    | '/needs'
    | '/surveys'
    | '/volunteers'
    | '/forms/$id/view'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/bulk-upload'
    | '/change-password'
    | '/chat'
    | '/login'
    | '/map'
    | '/settings'
    | '/smart-drive'
    | '/upload-hub'
    | '/volunteer-dashboard'
    | '/needs/$id'
    | '/needs/new'
    | '/surveys/$id'
    | '/surveys/new'
    | '/volunteers/$id'
    | '/volunteers/new'
    | '/needs/'
    | '/surveys/'
    | '/volunteers/'
    | '/forms/$id/view'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  BulkUploadRoute: typeof BulkUploadRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  ChatRoute: typeof ChatRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  SettingsRoute: typeof SettingsRoute
  SmartDriveRoute: typeof SmartDriveRoute
  UploadHubRoute: typeof UploadHubRoute
  VolunteerDashboardRoute: typeof VolunteerDashboardRoute
  NeedsIdRoute: typeof NeedsIdRoute
  NeedsNewRoute: typeof NeedsNewRoute
  SurveysIdRoute: typeof SurveysIdRoute
  SurveysNewRoute: typeof SurveysNewRoute
  VolunteersIdRoute: typeof VolunteersIdRoute
  VolunteersNewRoute: typeof VolunteersNewRoute
  NeedsIndexRoute: typeof NeedsIndexRoute
  SurveysIndexRoute: typeof SurveysIndexRoute
  VolunteersIndexRoute: typeof VolunteersIndexRoute
  FormsIdViewRoute: typeof FormsIdViewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulk-upload': {
      id: '/bulk-upload'
      path: '/bulk-upload'
      fullPath: '/bulk-upload'
      preLoaderRoute: typeof BulkUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-drive': {
      id: '/smart-drive'
      path: '/smart-drive'
      fullPath: '/smart-drive'
      preLoaderRoute: typeof SmartDriveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload-hub': {
      id: '/upload-hub'
      path: '/upload-hub'
      fullPath: '/upload-hub'
      preLoaderRoute: typeof UploadHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer-dashboard': {
      id: '/volunteer-dashboard'
      path: '/volunteer-dashboard'
      fullPath: '/volunteer-dashboard'
      preLoaderRoute: typeof VolunteerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/needs/': {
      id: '/needs/'
      path: '/needs'
      fullPath: '/needs/'
      preLoaderRoute: typeof NeedsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/needs/$id': {
      id: '/needs/$id'
      path: '/needs/$id'
      fullPath: '/needs/$id'
      preLoaderRoute: typeof NeedsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/needs/new': {
      id: '/needs/new'
      path: '/needs/new'
      fullPath: '/needs/new'
      preLoaderRoute: typeof NeedsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surveys/': {
      id: '/surveys/'
      path: '/surveys'
      fullPath: '/surveys/'
      preLoaderRoute: typeof SurveysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surveys/$id': {
      id: '/surveys/$id'
      path: '/surveys/$id'
      fullPath: '/surveys/$id'
      preLoaderRoute: typeof SurveysIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surveys/new': {
      id: '/surveys/new'
      path: '/surveys/new'
      fullPath: '/surveys/new'
      preLoaderRoute: typeof SurveysNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteers/': {
      id: '/volunteers/'
      path: '/volunteers'
      fullPath: '/volunteers/'
      preLoaderRoute: typeof VolunteersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteers/$id': {
      id: '/volunteers/$id'
      path: '/volunteers/$id'
      fullPath: '/volunteers/$id'
      preLoaderRoute: typeof VolunteersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteers/new': {
      id: '/volunteers/new'
      path: '/volunteers/new'
      fullPath: '/volunteers/new'
      preLoaderRoute: typeof VolunteersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/$id/view': {
      id: '/forms/$id/view'
      path: '/forms/$id/view'
      fullPath: '/forms/$id/view'
      preLoaderRoute: typeof FormsIdViewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  BulkUploadRoute: BulkUploadRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  ChatRoute: ChatRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  SettingsRoute: SettingsRoute,
  SmartDriveRoute: SmartDriveRoute,
  UploadHubRoute: UploadHubRoute,
  VolunteerDashboardRoute: VolunteerDashboardRoute,
  NeedsIdRoute: NeedsIdRoute,
  NeedsNewRoute: NeedsNewRoute,
  SurveysIdRoute: SurveysIdRoute,
  SurveysNewRoute: SurveysNewRoute,
  VolunteersIdRoute: VolunteersIdRoute,
  VolunteersNewRoute: VolunteersNewRoute,
  NeedsIndexRoute: NeedsIndexRoute,
  SurveysIndexRoute: SurveysIndexRoute,
  VolunteersIndexRoute: VolunteersIndexRoute,
  FormsIdViewRoute: FormsIdViewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
