// Vercel Serverless Function entry point.
// api/serverless-bundle/app.cjs is generated by `pnpm run build`
// It's a self-contained CJS bundle of the Express app with all dependencies bundled.
const bundle = require("./serverless-bundle/app.cjs");
const app = bundle.default || bundle;

module.exports = function handler(req, res) {
  try {
    return app(req, res);
  } catch (err) {
    console.error("Vercel handler error:", err);
    res.status(500).json({ error: "serverless_error", message: String(err?.message || err) });
  }
};
